[workspace]
resolver = "2"
members = [
    "crates/mutagen-core",
    "crates/mutagen-runtime",
    "crates/mutagen-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "Apache-2.0"
repository = "https://github.com/z-chenhao/Mutagen"
authors = ["z-chenhao"]

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -100 }
